{
 "title": "Simple Logs Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Log Ingestion Count over time",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count_over_time({event=~\".+\"}[$__interval]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Log Ingestion Size over time",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({event=~\".+\"}[$__interval]))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({event=~\".+\"}[$__range])) by (resource)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 19, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "{event=~\".+\"} |= `$search` | json | line_format \"{{(printf \\\"%s\\\" .message)}}\""
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(count_over_time({event=~\".+\"}[$__range])) by (event)"
    }
   ]
  }
 ]
}